
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      // Inserts seed entries
      return knex('users').insert([
        {id: 1, username: 'Carla', img_url: `http://www.thetrapset.net/wp-content/uploads/2014/12/carla_aLux-2.jpg`, email: 'carla@autolux.com', hashed_password: '$2a$10$c42r5/MrzAuhdAqlmAl69Ovr6oWcZU2RiTy9.7SXiIcrRytZ0yNaG', deal: `Posthuman drumbot sent from the future; mission unknown, awaiting command.`, genre_1: 'Alt', genre_2: 'Experimental', bio: `In a cool band and have sweet touring gig. On hiatus right now so seeing what's out there. I have a screw in my arm!`, heroes: 'Keith Moon', influences: 'PJ Harvey, Aphex Twin, Chemical Brothers', instr_1: 'Drums', instr_2: 'Vocals'},
        {id: 2, username: 'Jack', img_url: `https://cdn1.thr.com/sites/default/files/imagecache/landscape_928x523/2012/07/jack_white_a_l.jpg`, email: 'jack@white.com', hashed_password: '$2a$10$fkDjox8SnMnQ.xbZCX9dCuhezQgb0kTuDKoSZ8d6nDehbSgl7eOA2', deal: `Just looking for a bad-yet-compelling drummer who is my ex-wife`, genre_1: 'Alt', genre_2: 'Blues-rock', bio: `I use to do upholstery or something for a living but now have a pretty good little thing going. My band before had an ex-wife drummer like I mentioned so looking to recapture that with a new one.`, heroes: 'Robert Plant', influences: 'Robert Johnson, The Sonics, all of the blues', instr_1: 'Guitar', instr_2: 'Vocals', instr_3: 'Drums'},
        {id: 3, username: 'Cassie', img_url: `http://www.brooklynvegan.com/files/img/music/babies/deathbyaudio/7.jpg`, email: 'cassie@viviangirls.com', hashed_password: 'pw', deal: `Just your typical lo-fi-post-punk-noise-pop-dream-garage singer/songwriter in Brooklyn`, genre_1: 'Punk', genre_2: 'Noise-pop', bio: `I was in a legendary band that changed all of music forever that you probably never heard of a while back`, heroes: 'Greg Sage', influences: 'The Wipers, Nirvana, Ramones', instr_1: 'Guitar', instr_2: 'Vocals'},
        {id: 4, username: 'Scott', img_url: `https://www.bassplayer.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_600/MTUzNjY4MjY5MTAxMjk0NjQ4/image-placeholder-title.webp`, email: 'scott@kyuss.com', hashed_password: 'pw', deal: `always find a groove & you'll never see my face. that's the Scott guarantee!`, genre_1: 'Stoner Rock', genre_2:'Metal', heroes: 'Lemmy, Mike Watt', influences: 'Sabbath, Deep Purple, Cream', instr_1: 'Bass'},
        {id: 5, username: 'Brooks', img_url: `https://alchetron.com/cdn/brooks-wackerman-6b7f4926-1809-4c68-afba-036fea08666-resize-750.jpeg`, email: 'brooks@avenged.com', hashed_password: 'pw', deal: `I am the greatest drummer in the world.`, genre_1: 'Punk', genre_2: 'Metal', bio: `Left that guy Andrew's favorite band to join some dumb metal band. Huge mistake, not working out. Looking to get back into punk.`, heroes: 'Josh Freese, Pete Finestone', influences: 'Pennywise, The Descendants, Suicidal Tendencies', instr_1: 'Drums', instr_2: 'Guitar'},
        {id: 6, username: 'Tobias', img_url: `https://i.iheart.com/v3/re/new_assets/5bd1d3cc68578ca100357b0f?ops=max(650,0),quality(80)`, email: 'tobias@ghost.com', hashed_password: 'pw', deal: `I merely wish to operatically rock in service of our Dark Lord.`, genre_1: 'Metal', bio: `So yeah, I worship the devil, you don't have to, just to get it out of the way. If you do, great! It's just hard enough to find good help as it is, you know. I'm really not looking for creative partners, just musicians. I already made the album and played everything, and you have to be willing to play it to my exacting specifications. But I promise I'm actually a nice guy! Just make sure you dig the stuff. Also you have to wear a mask. I'm singing, Need 2 guitars, bass, drums, keys. Competitive salary + benefits.`, 
            heroes: 'Bruce Dickinson, Dave Mustaine', influences: 'Iron Maiden, Bathory, Metallica, Slayer, Rocky Erickson, Kiss, Blue Oyster Cult, Queen, ', instr_1: 'Vocals'},
        {id: 7, username: 'Lou', img_url: `http://www.motifri.com/wp-content/uploads/2015/06/LouBarlow.jpg`, email: 'lou@sebadoh.com', hashed_password: 'pw', deal: `Oh gosh, who knows man. Frustrated songwriter yearning to break free? Yeah.`, genre_1: 'Indie', genre_2: 'Lo-fi', genre_3: 'Folk', bio: `I'm in a band that's getting a lot of hype and stuff but the thing is I'm just playing bass, but I can write songs, and I don't get to. So I wanna start something on the side where everyone is friends and equals we get to do whatever we want. Maybe we even switch instruments on different songs and stuff. No rules! And definitely never ever signing to a major. Let's just do what we love and see what happens (apart from signing to a major).`, 
          heroes: 'Neil Young', influences: 'Neil Young, Sonic Youth, Meat Puppets, The Wipers', instr_1: 'Bass', instr_2: 'Vocals', instr_3: 'Baritone Ukulele'},
        {id: 8, username: 'Gary', img_url: `https://ksr-ugc.imgix.net/assets/019/710/212/5529dd61d864a85dd04136292a06930e_original.jpg?ixlib=rb-1.1.0&crop=faces&w=1552&h=873&fit=crop&v=1517267763&auto=format&frame=1&q=92&s=dbb830d9ac02b323c3b67de950385d4e`, email: 'gary@someguy.com', hashed_password: 'pw', deal: `Garyin' it up. Who's in? Gary with me!`, genre_1: 'Classic Rock', genre_2: 'Grunge', bio: `I've always played, had a few garage bands, but never got anything off the ground, had kids and a solid job at the factory in town and stuff. But that's all over now, cause I got laid off and divorced and it's mid-life crisis time! Nothing standing in my way! If you feel me let's grab a couple brewskis and dust off those amps. Oh also it'd be cool if everyone was named Gary. The Garys! lol`, 
          heroes: 'Jim Morrison, Eric Clapton, Dean DeLeo', influences: 'The Stones, Dylan, Clapton, Stone Temple Pilots, Pearl Jam, Guns N Roses, Husker Du/Bob Mould solo', instr_1: 'Guitar', instr_2: 'Vocals'},
        {id: 9, username: 'Emily', img_url: `https://www.flare.com/wp-content/uploads/2010/08/23e5eef2408ebe2c96dd18247ddf.jpeg`, email: 'emily@metric.com', hashed_password: 'pw', deal: `slow sad piano songs and/or synth-driven post-punk anthems`, genre_1: 'Indie', genre_2: 'Synthpop', bio: `I have an electronic duo and realized I want bass and drums after all. So if you dig it and feel like you could bring something, I'd love to meet you. Also, live in our loft with us if you want, we could stand to have a little more help with the rent. `, 
          heroes: 'Lou Reed, Envy Adams', influences: 'The Clash at Demonhead, Velvet Underground, Blade Runner', instr_1: 'Vocals', instr_2: 'Synths', instr_3: 'Piano'},
        {id: 10, username: 'Jehnny Beth', img_url: `https://cdn2.thelineofbestfit.com/images/made/images/remote/https_cdn2.thelineofbestfit.com/media/2014/jehnny_beth_savages_1290_857.png`, email: 'jhenny@savages.com', hashed_password: 'pw', deal: `Seeking a vital, revolutionary energy with which to pry open the eyes of those who would sew mine shut.`, genre_1: 'Punk', bio: `Some might call me severe--I say they don't know what it is to love, or to live, or that those are one in the same, and also the same as despair, and death. Only through art can we navigate it all. Looking for a good crew and a sinking ship.`, 
          heroes: 'God Herself', influences: 'Siouxsie and the Banshees, Joy Division, John Cassavetes', instr_1: 'Vocals'},
        {id: 11, username: 'Brant', img_url: `https://c1.staticflickr.com/1/363/18961017190_4974bce34e_b.jpg`, email: 'brant@kyuss.com', hashed_password: 'pw', deal: `Newly solo frontman looking for band`, genre_1: 'Desert Rock', genre_2: 'Psychedelia', bio: `Longtime drummer in some good bands, but time to branch out and live my real dream of being out front. The act is gonna be "Brant and the..." somethings. Y'all can pick what you wanna be. Cause see, I get what it's like to not be the Guy! Got a drummer, need other stuff. Ooh anyone on here play theremin and flute? That'd be sick man.`, 
          heroes: 'Jimi Hendrix, Danzig', influences: 'Hendrix, Kyuss, Samhain, Bob Marley, Earthlings', instr_1: 'Vocals', instr_2: 'Guitar'},
        {id: 12, username: 'Adam', img_url: `https://vignette.wikia.nocookie.net/rock/images/5/5e/Adamcarson.jpg/revision/latest?cb=20060923174741`, email: 'adam@afi.com', hashed_password: 'pw', deal: `Veteran hardcore drummer in famous-ish band but my needs are not being met`, genre_1: 'Hardcore', genre_2: 'Punk', genre_3: 'Psychobilly', bio: `My friends went all melodic/new-wave on me. And they're great at it. But I'm just the drummer and I can't exactly stretch my arms on your latest Cure homage dude. That's where you come in! And fwiw, we'll get a bump...Brooklyn Vegan headline, "Ex-[my old band] drummer announces new project [our new band], tour and EP to come." Send me some riffs and let's do it.`, 
          heroes: 'DH Peligro, Bill Stevenson', influences: 'Misfits, Dead Kennedys, Black Flag, Bad Brains', instr_1: 'Drums'},
        {id: 13, username: 'Will', img_url: `https://media.gettyimages.com/photos/william-goldsmith-of-sunny-day-real-estate-performs-on-day-3-of-the-picture-id98532572?k=6&m=98532572&s=594x594&w=0&h=ayXnEL4g_A-rTkpVClOMNfTtXhHqHOMHaWJhVZNwmvQ=`, email: 'will@foo.com', hashed_password: 'pw', deal: `Solid drummer here, just looking for a little appreciation and respect`, genre_1: 'Rock', genre_2: 'Alt', bio: `So I'm in this band where the singer also plays drums, like really well, better than I can, but I'm the drummer. We record the album, he goes away to mix it, and I finally hear it and he re-did all my parts without telling me. So just looking for a friendlier situation, preferrably with no one in the band who is better at drums than me. Or at least just be transparent with me if you are. But I'm pretty solid!`, 
          heroes: 'Phil Collins', influences: 'Genesis, Nirvana, Led Zeppelin, Motorhead, Rites of Spring', instr_1: 'Drums'},
          {id: 14, username: 'Carlos', img_url: `https://ksassets.timeincuk.net/wp/uploads/sites/55/2015/08/2015CarlosD_Interpol_GettyImages-84856316180815-3.jpg`, email: 'carlos@interpol.com', hashed_password: 'pw', deal: `Bassist/up for anything/let's get this show on the road already`, genre_1: 'Indie', genre_2: 'Alt', bio: `Yeah I play the bass, you do whatever you do, we realize we really have something special on our hands, BOOM let's go. When do we get in the studio, when does the tour start, when can I quit temping?`, heroes: 'Peter Hook', influences: 'Joy Division, New Order', instr_1: 'Bass'},
          {id: 15, username: 'Liam', img_url: `https://bc.marfeel.com/statics/i/ps/static.gigwise.com/artists/uewew976.jpg`, email: 'liam@prodigy.com', hashed_password: 'pw', deal: `Sampled every bloody thing in the world unless you've got something new`, genre_1: 'Electronic', genre_2: 'Big Beat', bio: `I like to sample real instruments these days, but it's become a tad tired. If you do something cool or just strange that I could use, let's book a session. It's a great form of collaboration for you, just make a couple noises and I do the rest and maybe you get a couple points.`, 
          influences: 'Public Enemy, Cybotron, Rage', instr_1: 'DJ/Producer', instr_2: 'Synths'},

      
      
      ]);
    }).then(() => {
      return knex.raw(
        `SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));`
      )
    })
};
