
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      // Inserts seed entries
      return knex('users').insert([
        {id: 1, username: 'Carla', img_url: `http://www.thetrapset.net/wp-content/uploads/2014/12/carla_aLux-2.jpg`, email: 'carla@autolux.com', hashed_password: '$2a$10$c42r5/MrzAuhdAqlmAl69Ovr6oWcZU2RiTy9.7SXiIcrRytZ0yNaG', deal: `I like to play real drums like they're electronic`, genre_1: 'Alt', genre_2: 'Experimental', bio: `In a cool band and have sweet touring gig. On hiatus right now so seeing what's out there. I have a screw in my arm!`, heroes: 'Keith Moon', influences: 'PJ Harvey, Aphex Twin, Chemical Brothers', instr_1: 'Drums', instr_2: 'Vocals', looking_1: 'Guitar', looking_2: 'Synths', looking_3: 'Bass'},
        {id: 2, username: 'Jack', img_url: `https://cdn1.thr.com/sites/default/files/imagecache/landscape_928x523/2012/07/jack_white_a_l.jpg`, email: 'jack@white.com', hashed_password: 'pw', deal: `Just looking for a bad-yet-compelling drummer who is my ex-wife`, genre_1: 'Alt', genre_2: 'Blues-rock', bio: `I use to do upholstery or something for a living but now have a pretty good little thing going. My band before had an ex-wife drummer like I mentioned so looking to recapture that with a new one.`, heroes: 'Robert Plant', influences: 'Robert Johnson, The Sonics, all of the blues', instr_1: 'Guitar', instr_2: 'Vocals', instr_3: 'Drums', looking_1: 'Drums'},
        {id: 3, username: 'Cassie', img_url: `http://www.brooklynvegan.com/files/img/music/babies/deathbyaudio/7.jpg`, email: 'cassie@viviangirls.com', hashed_password: 'pw', deal: `Just your typical lo-fi-post-punk-noies-pop-dream-garage singer/songwriter in Brooklyn`, genre_1: 'Punk', genre_2: 'Noise-pop', bio: `I was in a legendary band that changed all of music forever that you probably never heard of a while back`, heroes: 'Greg Sage', influences: 'The Wipers, Nirvana, Ramones', instr_1: 'Guitar', instr_2: 'Vocals', looking_1: 'Bass', looking_2: 'Drums'},
        {id: 4, username: 'Nick', img_url: `http://townsquare.media/site/366/files/2012/03/Nick-Oliveri1.jpg?w=980&q=75`, email: 'nick@nick.com', hashed_password: 'pw', deal: 'I can change I swear!', genre_1: 'Stoner Rock', genre_2:'Punk', genre_3: 'Metal', bio: `I keep getting kicked out of bands due to substance abuse issues, standoffs w/SWAT teams, etc. But all of that ends right now! A great buy-low candidate.`, heroes: 'Lemmy', influences: 'The Dwarves, Black Flag, Sabbath', instr_1: 'Bass', instr_2: 'Vocals', looking_1: 'All'},
        {id: 5, username: 'Brooks', img_url: `https://alchetron.com/cdn/brooks-wackerman-6b7f4926-1809-4c68-afba-036fea08666-resize-750.jpeg`, email: 'brooks@avenged.com', hashed_password: 'pw', deal: `I am literally the greatest drummer in the world.`, genre_1: 'Punk', genre_2: 'Metal', genre_3: 'Jazz', bio: `Left that guy Andrew's favorite band to join some dumb metal band. Huge mistake, not working out. Looking to get back into punk.`, heroes: 'Josh Freese, Pete Finestone', influences: 'Pennywise, The Descendants, Suicidal Tendencies', instr_1: 'Drums', instr_2: 'Guitar', looking_1: 'All'},
        {id: 6, username: 'Tobias', img_url: `https://i.iheart.com/v3/re/new_assets/5bd1d3cc68578ca100357b0f?ops=max(650,0),quality(80)`, email: 'tobias@ghost.com', hashed_password: 'pw', deal: `I merely wish to operatically rock in service of our Dark Lord.`, genre_1: 'Metal', bio: `So yeah, I worship the devil, you don't have to, just to get it out of the way. If you do, great! It's just hard enough to find good help as it is, you know. I'm really not looking for creative partners, just musicians. I already made the album and played everything, and you have to be willing to play it to my exacting specifications. But I promise I'm actually a nice guy! Just make sure you dig the stuff. Also you have to wear a mask. I'm singing, Need 2 guitars, bass, drums, keys. Pay is pretty decent.`, 
            heroes: 'Bruce Dickinson, Dave Mustaine', influences: 'Iron Maiden, Bathory, Metallica, Slayer, Rocky Erickson, Kiss, Blue Oyster Cult, Queen, ', instr_1: 'Vocals', instr_2: 'Guitar', instr_3: 'Drums'},
        {id: 7, username: 'Lou', img_url: `http://www.motifri.com/wp-content/uploads/2015/06/LouBarlow.jpg`, email: 'lou@sebadoh.com', hashed_password: 'pw', deal: `Oh gosh, who knows man. Frustrated songwriter yearning to break free? Yeah.`, genre_1: 'Indie', genre_2: 'Lo-fi', genre_3: 'Folk', bio: `I'm in a band that's getting a lot of hype and stuff but the thing is I'm just playing bass, but I can write songs, and I don't get to. So I wanna start something on the side where everyone is friends and equals we get to do whatever we want. Maybe we even switch instruments on different songs and stuff. No rules! And definitely never ever signing to a major. Let's just do what we love and see what happens (apart from signing to a major).`, 
          heroes: 'Josh Freese, Pete Finestone', influences: 'Pennywise, The Descendants, Suicidal Tendencies', instr_1: 'Drums', instr_2: 'Guitar', looking_1: 'All'},
        {id: 8, username: 'Gary', img_url: `https://ksr-ugc.imgix.net/assets/019/710/212/5529dd61d864a85dd04136292a06930e_original.jpg?ixlib=rb-1.1.0&crop=faces&w=1552&h=873&fit=crop&v=1517267763&auto=format&frame=1&q=92&s=dbb830d9ac02b323c3b67de950385d4e`, email: 'gary@someguy.com', hashed_password: 'pw', deal: `Garyin' it up. Who's in? Gary with me!`, genre_1: 'Classic Rock', genre_2: 'Grunge', bio: `I've always played, had a few garage bands, but never got anything off the ground, had kids and a solid job at the factory in town and stuff. But that's all over now, cause I got laid off and divorced and it's mid-life crisis time! Nothing standing in my way! If you feel me let's grab a couple brewskis and dust off those amps. Oh also it'd be cool if everyone was named Gary. The Garys! lol`, 
          heroes: 'Jim Morrison, Eric Clapton, Dean DeLeo', influences: 'The Stones, Dylan, Clapton, Stone Temple Pilots, Pearl Jam, Guns N Roses, Husker Du/Bob Mould solo', instr_1: 'Guitar', instr_2: 'Vocals'},
        {id: 9, username: 'Emily', img_url: `https://www.flare.com/wp-content/uploads/2010/08/23e5eef2408ebe2c96dd18247ddf.jpeg`, email: 'emily@metric.com', hashed_password: 'pw', deal: `slow sad piano songs and/or synth-driven post-punk anthems`, genre_1: 'Indie', genre_2: 'Synthpop', bio: `I have an electronic duo and realized I want bass and rums after all. So if you dig it and feel like you could bring something, I'd love to meet you. Also, live in our loft with us if we want, we could stand to have a little more help with the rent. `, 
          heroes: 'Lou Reed, Envy Adams', influences: 'The Clash at Demonhead, Velvet Underground, Blade Runner', instr_1: 'Vocals', instr_2: 'Synths', instr_3: 'Piano'},
        {id: 10, username: 'Jehnny Beth', img_url: `https://cdn2.thelineofbestfit.com/images/made/images/remote/https_cdn2.thelineofbestfit.com/media/2014/jehnny_beth_savages_1290_857.png`, email: 'jhenny@savages.com', hashed_password: 'pw', deal: `Seeking vital, revolutionary energy with which to open the eyes of the world`, genre_1: 'Punk', bio: `Some might call me severe--I say they don't know what it is to love, or to live, or that those are one in the same, and also the same as despair, and death. Only through art can we navigate it all. Looking a crew and a sinking ship.`, 
          heroes: 'God Herself', influences: 'Siouxsie and the Banshees, Joy Division, John Cassavetes', instr_1: 'Vocals'},
      
      ]);
    }).then(() => {
      return knex.raw(
        `SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));`
      )
    })
};
